### ISSUE TITLE
Bar-U-Eat staff can establish universal goals/milestones

### ISSUE THREAD

**Issue by ngottlieb** [ngottlieb/thecarfreechallenge#9]
- [x] create data structure for milestones (universal, so different from user goals)
- [x] create administrative interface for Bar-U-Eat staff to control milestones
- [x] automatically send notifications about milestone achievements to Bar-U-Eat staff
- [x] allow users to see the milestones they've collected
- [x] allow users to see all available milestones

**Comment by ngottlieb** [comment]
Still to-do:

- [x] allow users to opt in or out of bar-u-eat prizes/emailing
- [x] add ability for bar-u-eat staff to add "badge" images for milestones and display them to users
- [x] after #8, incorporate more user information into the notice email that goes to bar-u-eat
